@setlocal

pushd %1
@set ExePath=%~fd0\..\tools\jsonNewlineByArr.cpp.exe
@set DataRoot=data

%ExePath% %DataRoot%\Actors.json 
%ExePath% %DataRoot%\Animations.json 1 2 
%ExePath% %DataRoot%\Armors.json 
%ExePath% %DataRoot%\Classes.json 1 2 
%ExePath% %DataRoot%\CommonEvents.json 1 2 
%ExePath% %DataRoot%\Enemies.json 
%ExePath% %DataRoot%\Items.json 
%ExePath% %DataRoot%\MapInfos.json 
%ExePath% %DataRoot%\Skills.json 
%ExePath% %DataRoot%\States.json 
%ExePath% %DataRoot%\System.json 
%ExePath% %DataRoot%\Tilesets.json 1 
%ExePath% %DataRoot%\Troops.json 1 2 3 
%ExePath% %DataRoot%\Weapons.json 

%ExePath% %DataRoot%\Map001.json 
%ExePath% %DataRoot%\Map002.json 
%ExePath% %DataRoot%\Map003.json 
%ExePath% %DataRoot%\Map004.json 
%ExePath% %DataRoot%\Map005.json 
%ExePath% %DataRoot%\Map006.json 
%ExePath% %DataRoot%\Map007.json 
%ExePath% %DataRoot%\Map008.json 
%ExePath% %DataRoot%\Map009.json 
%ExePath% %DataRoot%\Map010.json 
%ExePath% %DataRoot%\Map011.json 
%ExePath% %DataRoot%\Map012.json 
%ExePath% %DataRoot%\Map013.json 
%ExePath% %DataRoot%\Map014.json 
%ExePath% %DataRoot%\Map015.json 
%ExePath% %DataRoot%\Map016.json 
%ExePath% %DataRoot%\Map017.json 
%ExePath% %DataRoot%\Map018.json 
%ExePath% %DataRoot%\Map019.json 
%ExePath% %DataRoot%\Map020.json 
%ExePath% %DataRoot%\Map021.json 
%ExePath% %DataRoot%\Map022.json 
%ExePath% %DataRoot%\Map023.json 
%ExePath% %DataRoot%\Map024.json 
%ExePath% %DataRoot%\Map025.json 
%ExePath% %DataRoot%\Map026.json 
%ExePath% %DataRoot%\Map027.json 
%ExePath% %DataRoot%\Map028.json 
%ExePath% %DataRoot%\Map029.json 
%ExePath% %DataRoot%\Map030.json 
%ExePath% %DataRoot%\Map031.json 
%ExePath% %DataRoot%\Map032.json 
%ExePath% %DataRoot%\Map033.json 
%ExePath% %DataRoot%\Map034.json 
%ExePath% %DataRoot%\Map035.json 
%ExePath% %DataRoot%\Map036.json 
%ExePath% %DataRoot%\Map037.json 
%ExePath% %DataRoot%\Map038.json 
%ExePath% %DataRoot%\Map039.json 
%ExePath% %DataRoot%\Map040.json 
%ExePath% %DataRoot%\Map041.json 
%ExePath% %DataRoot%\Map042.json 
%ExePath% %DataRoot%\Map043.json 
%ExePath% %DataRoot%\Map044.json 
%ExePath% %DataRoot%\Map045.json 
%ExePath% %DataRoot%\Map046.json 
%ExePath% %DataRoot%\Map047.json 
%ExePath% %DataRoot%\Map048.json 
%ExePath% %DataRoot%\Map049.json 
%ExePath% %DataRoot%\Map050.json 
%ExePath% %DataRoot%\Map051.json 
%ExePath% %DataRoot%\Map052.json 
%ExePath% %DataRoot%\Map053.json 
%ExePath% %DataRoot%\Map054.json 
%ExePath% %DataRoot%\Map055.json 
%ExePath% %DataRoot%\Map056.json 
%ExePath% %DataRoot%\Map057.json 
%ExePath% %DataRoot%\Map058.json 
%ExePath% %DataRoot%\Map059.json 
%ExePath% %DataRoot%\Map060.json 
%ExePath% %DataRoot%\Map061.json 
%ExePath% %DataRoot%\Map062.json 
%ExePath% %DataRoot%\Map063.json 
%ExePath% %DataRoot%\Map064.json 
%ExePath% %DataRoot%\Map065.json 
%ExePath% %DataRoot%\Map066.json 
%ExePath% %DataRoot%\Map067.json 
%ExePath% %DataRoot%\Map068.json 
%ExePath% %DataRoot%\Map069.json 
%ExePath% %DataRoot%\Map070.json 
%ExePath% %DataRoot%\Map071.json 
%ExePath% %DataRoot%\Map072.json 
%ExePath% %DataRoot%\Map073.json 
%ExePath% %DataRoot%\Map074.json 
%ExePath% %DataRoot%\Map075.json 
%ExePath% %DataRoot%\Map076.json 
%ExePath% %DataRoot%\Map077.json 
%ExePath% %DataRoot%\Map078.json 
%ExePath% %DataRoot%\Map079.json 
%ExePath% %DataRoot%\Map080.json 
%ExePath% %DataRoot%\Map081.json 
%ExePath% %DataRoot%\Map082.json 
%ExePath% %DataRoot%\Map083.json 
%ExePath% %DataRoot%\Map084.json 
%ExePath% %DataRoot%\Map085.json 
%ExePath% %DataRoot%\Map086.json 
%ExePath% %DataRoot%\Map087.json 
%ExePath% %DataRoot%\Map088.json 
%ExePath% %DataRoot%\Map089.json 
%ExePath% %DataRoot%\Map090.json 
%ExePath% %DataRoot%\Map091.json 
%ExePath% %DataRoot%\Map092.json 
%ExePath% %DataRoot%\Map093.json 
%ExePath% %DataRoot%\Map094.json 
%ExePath% %DataRoot%\Map095.json 
%ExePath% %DataRoot%\Map096.json 
%ExePath% %DataRoot%\Map097.json 
%ExePath% %DataRoot%\Map098.json 
%ExePath% %DataRoot%\Map099.json 
%ExePath% %DataRoot%\Map100.json 

